name: signal
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.5



  # Local Database :
  shared_preferences: ^2.2.0

  # Responsive UI :
  responsive_sizer: ^3.1.1
  device_preview: ^1.1.0

  # Web module :
  url_launcher: ^6.1.7
  share_plus: ^7.1.0

  # Image View :
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  #shimmer effect
  shimmer: ^3.0.0

  #image Picker :
  image_picker: ^1.0.2

  #slidable massge :
  flutter_slidable: ^3.0.0
  chat_bubbles: ^1.5.0
  flutter_chat_bubble: ^2.0.2
  sticky_headers: ^0.3.0+2
  grouped_list: ^5.1.2

  #serchField
  flutter_typeahead: ^4.6.2



  # Fetch server data & State management :
  get: ^4.6.5
  connectivity: ^3.0.6


  # contact numbers
  contacts_service: ^0.6.3


  # permissions
  permission_handler: ^10.4.3
  country_code_picker: ^3.0.0
  pinput: ^3.0.0

  #firebase :
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.6

  #sqflite Database
  sqflite: ^2.3.0

  # localization
  intl: ^0.18.0
  flutter_localization: ^0.1.13

  # text
  lorem_gen: ^2.0.1

  # version
  package_info_plus: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/


  fonts:
    - family: poppins
      fonts:
#        - asset: assets/fonts/poppins/Poppins-Black.ttf
#        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
#        - asset: assets/fonts/poppins/Poppins-Bold.ttf
#        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
#        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
#        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
#        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
#        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
#        - asset: assets/fonts/poppins/Poppins-Italic.ttf
#        - asset: assets/fonts/poppins/Poppins-Light.ttf
#        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
#        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
#        - asset: assets/fonts/poppins/Poppins-Regular.ttf
#        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
#        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
#        - asset: assets/fonts/poppins/Poppins-Thin.ttf
#        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
