name: signal
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.5



  # Local Database :
  shared_preferences: ^2.2.0

  # Responsive UI :
  responsive_sizer: ^3.1.1
  device_preview: ^1.1.0

  # Web module :
  url_launcher: ^6.1.7
  share_plus: ^7.1.0

  # Image View :
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0

  #shimmer effect
  shimmer: ^3.0.0

  #image Picker & cropper :
  image_picker: ^1.0.2
  image_cropper: ^5.0.0

  #slidable massge :
  flutter_slidable: ^3.0.0
  chat_bubbles: ^1.5.0
  flutter_chat_bubble: ^2.0.2
  sticky_headers: ^0.3.0+2
  grouped_list: ^5.1.2

  #serchField
  flutter_typeahead: ^4.6.2

  #audio
  on_audio_query: ^2.9.0
  just_audio: ^0.9.35

  #Video
  video_player: ^2.7.1


  # file
  file_picker: ^5.5.0



  # Fetch server data & State management :
  get: ^4.6.5
  connectivity: ^3.0.6






  # contact numbers
  contacts_service: ^0.6.3



  # screenshot disable
  flutter_windowmanager: ^0.2.0

  # permissions
  permission_handler: ^10.4.3
  country_code_picker: ^3.0.0
  pinput: ^3.0.0

  #firebase :
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.6
  firebase_messaging:
  fluttertoast: ^8.2.2

  #flutter Notification
  flutter_local_notifications: ^15.1.1




  #sqflite Database
  sqflite: ^2.3.0

  # localization
  intl: ^0.18.0
  flutter_localization: ^0.1.13

  # text
  lorem_gen: ^2.0.1

  # version
  package_info_plus: ^4.1.0
  widgets_to_image: ^0.0.2
  image: ^4.0.17
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
